In [1]:
import pandas as pd

In [9]:
base = pd.read_excel("ChavesClientes.xlsx", sheet_name = "base")

In [10]:
base.head()

   ID ChaveSituacao ClassRisco   CatCliente  Pagamento
0   1          32FC     Ccinza  Basic-Alpha          1
1   2          25MV   AAmarelo        Black          1
2   3          27MV  B-Amarelo   Basic-Beta          1
3   4          26FD   BAmarelo        Black          0
4   5          26FD  C-Amarelo        Black          0

In [12]:
base.groupby(["Pagamento","ChaveSituacao"])["Pagamento"].count()

Pagamento  ChaveSituacao
0          26FD             2
           28FC             2
           28MD             1
           30FC             1
           31MD             1
1          25FD             1
           25FV             1
           25MV             1
           26MC             2
           27MC             1
           27MD             2
           27MV             1
           28FS             1
           29MV             1
           31MV             1
           32FC             1
Name: Pagamento, dtype: int64

In [13]:
texto = "28FC"

In [14]:
texto[-1]

'C'

In [22]:
base['idade'] = base.ChaveSituacao.str[:2]
base['genero'] = base.ChaveSituacao.str[2:3]
base['estadocivil'] = base.ChaveSituacao.str[-1]

In [23]:
base.head()

,ID,ChaveSituacao,ClassRisco,CatCliente,Pagamento,idade,genero,estadocivil
0,1,32FC,Ccinza,Basic-Alpha,1,32,F,C
1,2,25MV,AAmarelo,Black,1,25,M,V
2,3,27MV,B-Amarelo,Basic-Beta,1,27,M,V
3,4,26FD,BAmarelo,Black,0,26,F,D
4,5,26FD,C-Amarelo,Black,0,26,F,D

In [24]:
texto = 'Basic-Alfa'

In [25]:
texto.split('-')

['Basic', 'Alfa']

In [26]:
base['categoria'] = base.CatCliente.str.split('-').str.get(0)
base['catvip'] = base.CatCliente.str.split('-').str.get(1)

In [27]:
base.head()

,ID,ChaveSituacao,ClassRisco,CatCliente,Pagamento,idade,genero,estadocivil,categoria,catvip
0,1,32FC,Ccinza,Basic-Alpha,1,32,F,C,Basic,Alpha
1,2,25MV,AAmarelo,Black,1,25,M,V,Black,NaN
2,3,27MV,B-Amarelo,Basic-Beta,1,27,M,V,Basic,Beta
3,4,26FD,BAmarelo,Black,0,26,F,D,Black,NaN
4,5,26FD,C-Amarelo,Black,0,26,F,D,Black,NaN

In [28]:
import re

In [29]:
base['risco'] = base.ClassRisco.apply(lambda x: re.findall('^[A-Z][^A-Za-z]?',x))

In [30]:
base.head()

,ID,ChaveSituacao,ClassRisco,CatCliente,Pagamento,idade,genero,estadocivil,categoria,catvip,risco
0,1,32FC,Ccinza,Basic-Alpha,1,32,F,C,Basic,Alpha,[C]
1,2,25MV,AAmarelo,Black,1,25,M,V,Black,NaN,[A]
2,3,27MV,B-Amarelo,Basic-Beta,1,27,M,V,Basic,Beta,[B-]
3,4,26FD,BAmarelo,Black,0,26,F,D,Black,NaN,[B]
4,5,26FD,C-Amarelo,Black,0,26,F,D,Black,NaN,[C-]

In [31]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             20 non-null     int64
 1   ChaveSituacao  20 non-null     object
 2   ClassRisco     20 non-null     object
 3   CatCliente     20 non-null     object
 4   Pagamento      20 non-null     int64
 5   idade          20 non-null     object
 6   genero         20 non-null     object
 7   estadocivil    20 non-null     object
 8   categoria      20 non-null     object
 9   catvip         8 non-null      object
 10  risco          20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [32]:
base['idade'] = pd.to_numeric(base['idade'])

In [33]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             20 non-null     int64
 1   ChaveSituacao  20 non-null     object
 2   ClassRisco     20 non-null     object
 3   CatCliente     20 non-null     object
 4   Pagamento      20 non-null     int64
 5   idade          20 non-null     int64
 6   genero         20 non-null     object
 7   estadocivil    20 non-null     object
 8   categoria      20 non-null     object
 9   catvip         8 non-null      object
 10  risco          20 non-null     object
dtypes: int64(3), object(8)
memory usage: 1.8+ KB

In [34]:
base.loc[base.catvip.isnull()]

,ID,ChaveSituacao,ClassRisco,CatCliente,Pagamento,idade,genero,estadocivil,categoria,catvip,risco
1,2,25MV,AAmarelo,Black,1,25,M,V,Black,NaN,[A]
3,4,26FD,BAmarelo,Black,0,26,F,D,Black,NaN,[B]
4,5,26FD,C-Amarelo,Black,0,26,F,D,Black,NaN,[C-]
7,8,31MD,C-Cinza,Basic,0,31,M,D,Basic,NaN,[C-]
8,9,28FS,A-Cinza,Black,1,28,F,S,Black,NaN,[A-]
9,10,31MV,C+Amarelo,Platinum,1,31,M,V,Platinum,NaN,[C+]
10,11,29MV,AAmarelo,Basic,1,29,M,V,Basic,NaN,[A]
12,13,28FC,Bverde,Basic,0,28,F,C,Basic,NaN,[B]
13,14,26MC,A-Verde,Platinum,1,26,M,C,Platinum,NaN,[A-]
15,16,27MC,B-Roxo,Platinum,1,27,M,C,Platinum,NaN,[B-]
16,17,25FD,A-Verde,Black,1,25,F,D,Black,NaN,[A-]
19,20,25FV,AAmarelo,Platinum,1,25,F,V,Platinum,NaN,[A]

In [36]:
base.loc[base.catvip.isnull(), "catvip"]="comum"

In [37]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             20 non-null     int64
 1   ChaveSituacao  20 non-null     object
 2   ClassRisco     20 non-null     object
 3   CatCliente     20 non-null     object
 4   Pagamento      20 non-null     int64
 5   idade          20 non-null     int64
 6   genero         20 non-null     object
 7   estadocivil    20 non-null     object
 8   categoria      20 non-null     object
 9   catvip         20 non-null     object
 10  risco          20 non-null     object
dtypes: int64(3), object(8)
memory usage: 1.8+ KB

In [39]:
base.groupby(["Pagamento","categoria"])["Pagamento"].count()

Pagamento  categoria
0          Basic        3
           Black        3
           Platinum     1
1          Basic        3
           Black        4
           Platinum     6
Name: Pagamento, dtype: int64

In [40]:
base.groupby(["Pagamento","catvip"])["Pagamento"].count()

Pagamento  catvip
0          Alpha     1
           Beta      2
           comum     4
1          Alpha     3
           Beta      2
           comum     8
Name: Pagamento, dtype: int64